image: node:lts

variables:
  TIMEZONE: "Europe/Berlin"


stages:
  - test
  - deployment

pages:
  variables:
    GIT_STRATEGY: clone
  stage: deployment
  script:
    - npm ci
    - FORCE_SHOW_EDIT_PAGE_LINK=true CI=true npm run documentation
    - mv build/docs public
  artifacts:
    paths:
      - public


test:
  image: ubuntu:latest
  stage: test
  script:
    - sh -c 'echo "127.0.0.11 proxy.local\n" >> /etc/hosts'
    - apt install curl
    - curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
    - source ~/.profile
    - nvm install 16 && nvm use 16 && nvm alias default 16
    - npm install -g npm@latest
    - npm ci
    - set -x
    - docker-compose -f deployments/testing/docker-compose.yml up -d
    - set -x
    - sleep 60
    - npm test
