// ---- Generated by gulp task ----

export {
  IIndexElasticApi,
  IIndexStorageRef,
  IIndexStorageRefOptions,
  IElasticStorageRefOptions,
  IIndexType,
  IElasticDeleteOptions,
  IElasticFieldDef,
  IElasticAggregateOptions,
  IElasticFindOptions,
  IElasticIndexOptions,
  TN_INDEX,
  TXS_SEARCH,
  XS_P_$AGGREGATION,
  XS_P_$FACETS,
  XS_P_$INDEX,
  XS_P_$MAX_SCORE,
  XS_P_$SCORE,
  ES_ALLFIELD,
  PERMISSION_ACCESS_SEARCH_VIEW,
  ES_IDFIELD,
  K_CLS_STORAGE_INDEX_TYPES,
  SEARCH_PAGE,
  ISearchFacet,
  IIndexRef,
  IEntityIndexRef,
  IIndexData, IElasticFacets, IElasticHighlight, IElasticSaveOptions, IElasticUpdateOptions, DEFAULT_FACET
} from './browser';

export { IndexElasticApi } from './api/IndexElastic.api';
export { IndexRuntimeStatus } from './lib/IndexRuntimeStatus';
export { IndexEntityRef } from './lib/registry/IndexEntityRef';
export { IndexEntityRegistry } from './lib/registry/IndexEntityRegistry';


export { ElasticEntityController } from './lib/elastic/ElasticEntityController';
export { ElasticStorageRef } from './lib/elastic/ElasticStorageRef';
export { ElasticUtils } from './lib/elastic/ElasticUtils';
export { ElasticMangoWalker } from './lib/elastic/ElasticMangoWalker';
export { ElasticConnection } from './lib/elastic/ElasticConnection';
