cluster.name: "docker-cluster"
network.host: 0.0.0.0
cluster.routing.allocation.disk.watermark.low: "30mb"
cluster.routing.allocation.disk.watermark.high: "20mb"
cluster.routing.allocation.disk.watermark.flood_stage: "10mb"
cluster.info.update.interval: "1m"
