version: 2.1
jobs:
  test:
#    docker:
#      - image: circleci/node:14
    machine:
      image: ubuntu-2204:current
    environment:
      TZ: Europe/Berlin
      NODE_OPTIONS: --openssl-legacy-provider

    working_directory: ~/app

    steps:
      - run:
          name: Update env
          command: |
            sudo sh -c 'echo "127.0.0.11 proxy.local\n" >> /etc/hosts'
      - run:
          name: NVM
          command: |
            nvm install 18 && nvm use 18 && nvm alias default 18
            node -v
            npm -v

      - checkout

      - run:
          name: Install npm wee
          command: npm ci

      - run:
          name: Start container
          command: |
            set -x
            docker-compose -f deployments/testing/docker-compose.local.yml up -d

      - run:
          name: Wait for containers to start
          command: |
            set -x
            sleep 60

      - run:
          name: Test
          command: npm test


# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - test
