version: '3'

services:

  redis:
    image: redis:5
    ports:
      - 127.0.0.1:6379:6379

  redis2:
    image: redis:5
    ports:
      - 127.0.0.1:6380:6379

  mongo:
    image: mongo:4
    ports:
      - 127.0.0.1:27017:27017

  elastic:
    image: elasticsearch:7.14.2
    environment:
      - TAKE_FILE_OWNERSHIP=true
      - discovery.type=single-node
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300

  psql:
    image: postgres:14
    ports:
      - 127.0.0.1:5436:5432
    environment:
      POSTGRES_DATABASES: txsbase
      POSTGRES_USER: txsbase
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:

  psql-auth:
    image: postgres:14
    ports:
      - 127.0.0.1:5437:5432
    environment:
      POSTGRES_DATABASES: auth
      POSTGRES_USER: auth
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:

  mysql:
    image: mysql:5
    ports:
      - 127.0.0.1:3306:3306
    command: --sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: txsbase
      MYSQL_USER: txsbase
      MYSQL_ROOT_PASSWORD: txsbase
      MYSQL_PASSWORD: txsbase


  ldap:
    image: osixia/openldap:1.2.2
    ports:
      - 127.0.0.1:389:389
      - 127.0.0.1:689:689
    environment:
      LDAP_NOFILE: 10000
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug
