export {
  API_CTRL_DISTRIBUTED_STORAGE,
  API_CTRL_DISTRIBUTED_STORAGE_DELETE_ENTITY,
  API_CTRL_DISTRIBUTED_STORAGE_FIND_ENTITY,
  API_CTRL_DISTRIBUTED_STORAGE_GET_ENTITY,
  _API_CTRL_DISTRIBUTED_STORAGE_DELETE_ENTITIES_BY_CONDITION,
  _API_CTRL_DISTRIBUTED_STORAGE_DELETE_ENTITY,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_UPDATE_ENTITY,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_DELETE_ENTITY_PATTERN,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_DELETE_ENTITY,
  _API_CTRL_DISTRIBUTED_STORAGE_UPDATE_ENTITY,
  _API_CTRL_DISTRIBUTED_STORAGE_UPDATE_ENTITIES_BY_CONDITION,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_SAVE_ENTITY,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_ACCESS_ENTITY,
  _API_CTRL_DISTRIBUTED_STORAGE_SAVE_ENTITY,
  _API_CTRL_DISTRIBUTED_STORAGE_GET_ENTITY,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_SAVE_ENTITY_PATTERN,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_UPDATE_ENTITY_PATTERN,
  _API_CTRL_DISTRIBUTED_STORAGE_FIND_ENTITY,
  PERMISSION_ALLOW_DISTRIBUTED_STORAGE_ACCESS_ENTITY_PATTERN,
  __DISTRIBUTED_ID__,
  __REMOTE_IDS__,
  API_CTRL_DISTRIBUTED_STORAGE_UPDATE_ENTITY,
  API_CTRL_DISTRIBUTED_STORAGE_SAVE_ENTITY,
  API_CTRL_DISTRIBUTED_STORAGE_DELETE_ENTITIES_BY_CONDITION,
  DS_OPERATION, XS_P_$SAVED, XS_P_$ERRORED, API_CTRL_DISTRIBUTED_STORAGE_UPDATE_ENTITIES_BY_CONDITION
} from './lib/Constants';
export { IDistributedFindOptions } from './lib/find/IDistributedFindOptions';
export { IDistributedAggregateOptions } from './lib/aggregate/IDistributedAggregateOptions';
export { IDistributedSaveOptions } from './lib/save/IDistributedSaveOptions';
export { IDistributedUpdateOptions } from './lib/update/IDistributedUpdateOptions';
export { IDistributedRemoveOptions } from './lib/remove/IDistributedRemoveOptions';
