import { _API_CTRL_SYSTEM } from '@typexs/server/libs/Constants';

/**
 * Storage Metadata
 */
export const API_CTRL_STORAGE_PREFIX = '/storage';


export const PERMISSION_ALLOW_ACCESS_STORAGE_METADATA = 'allow access storage metadata';
export const _API_CTRL_STORAGE_METADATA = '/metadata';

export const _API_CTRL_STORAGE_METADATA_ALL_STORES = _API_CTRL_STORAGE_METADATA + '/schemas';
export const API_CTRL_STORAGE_METADATA_ALL_STORES = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_METADATA_ALL_STORES;

export const _API_CTRL_STORAGE_METADATA_GET_STORE = _API_CTRL_STORAGE_METADATA + '/schema/:name';
export const API_CTRL_STORAGE_METADATA_GET_STORE = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_METADATA_GET_STORE;

export const _API_CTRL_STORAGE_METADATA_ALL_ENTITIES = _API_CTRL_STORAGE_METADATA + '/entities';
export const API_CTRL_STORAGE_METADATA_ALL_ENTITIES = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_METADATA_ALL_ENTITIES;

export const _API_CTRL_STORAGE_METADATA_CREATE_ENTITY = _API_CTRL_STORAGE_METADATA + '/entity';
export const API_CTRL_STORAGE_METADATA_CREATE_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_METADATA_CREATE_ENTITY;

export const _API_CTRL_STORAGE_METADATA_GET_ENTITY = _API_CTRL_STORAGE_METADATA + '/entity/:name';
export const API_CTRL_STORAGE_METADATA_GET_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_METADATA_GET_ENTITY;

export const _API_CTRL_STORAGE_FIND_ENTITY = '/find/:name';
export const API_CTRL_STORAGE_FIND_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_FIND_ENTITY;

export const _API_CTRL_STORAGE_AGGREGATE_ENTITY = '/aggregate/:name';
export const API_CTRL_STORAGE_AGGREGATE_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_AGGREGATE_ENTITY;

export const _API_CTRL_STORAGE_GET_ENTITY = '/entity/:name/:id';
export const API_CTRL_STORAGE_GET_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_GET_ENTITY;

export const PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY = 'allow access storage entity';
export const PERMISSION_ALLOW_ACCESS_STORAGE_ENTITY_PATTERN = 'allow access storage entity :name';

export const _API_CTRL_STORAGE_SAVE_ENTITY = '/save/:name';
export const API_CTRL_STORAGE_SAVE_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_SAVE_ENTITY;
export const PERMISSION_ALLOW_SAVE_STORAGE_ENTITY = 'allow save storage entity';
export const PERMISSION_ALLOW_SAVE_STORAGE_ENTITY_PATTERN = 'allow save storage entity :name';

export const _API_CTRL_STORAGE_UPDATE_ENTITY = '/update/:name/:id';
export const API_CTRL_STORAGE_UPDATE_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_UPDATE_ENTITY;
export const _API_CTRL_STORAGE_UPDATE_ENTITIES_BY_CONDITION = '/update/:name';

export const API_CTRL_STORAGE_UPDATE_ENTITIES_BY_CONDITION = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_UPDATE_ENTITIES_BY_CONDITION;
export const PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY = 'allow edit storage entity';
export const PERMISSION_ALLOW_UPDATE_STORAGE_ENTITY_PATTERN = 'allow edit storage entity :name';

export const _API_CTRL_STORAGE_DELETE_ENTITY = '/delete/:name/:id';
export const API_CTRL_STORAGE_DELETE_ENTITY = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_DELETE_ENTITY;

export const _API_CTRL_STORAGE_DELETE_ENTITIES_BY_CONDITION = '/update/:name';
export const API_CTRL_STORAGE_DELETE_ENTITIES_BY_CONDITION = API_CTRL_STORAGE_PREFIX + _API_CTRL_STORAGE_DELETE_ENTITIES_BY_CONDITION;

export const PERMISSION_ALLOW_DELETE_STORAGE_ENTITY = 'allow delete storage entity';
export const PERMISSION_ALLOW_DELETE_STORAGE_ENTITY_PATTERN = 'allow delete storage entity :name';


export const PERMISSION_ALLOW_STORAGES_VIEW = 'allow storages admin view';
export const _API_CTRL_SYSTEM_STORAGES = '/storages';
// export const API_CTRL_SYSTEM_STORAGES = _API_CTRL_SYSTEM + _API_CTRL_SYSTEM_STORAGES;
export const API_CTRL_SYSTEM_STORAGES = _API_CTRL_SYSTEM + _API_CTRL_SYSTEM_STORAGES;

export const PERMISSION_ALLOW_STORAGE_ENTITIES = 'allow storages admin entities';
// export const PERMISSION_ALLOW_STORAGE_VIEW_ENTITY = 'allow view storage entity';

export const _API_CTRL_SYSTEM_STORAGE_ENTITIES = '/storage/:name/entities';

export const API_CTRL_SYSTEM_STORAGE_ENTITIES = _API_CTRL_SYSTEM + _API_CTRL_SYSTEM_STORAGE_ENTITIES;



export const PERMISSION_ALLOW_STORAGE_TEST = 'allow storage admin test';

export const _API_CTRL_SYSTEM_STORAGE_TEST = '/storage/:idOrName/test';

export const API_CTRL_SYSTEM_STORAGE_TEST = _API_CTRL_SYSTEM + _API_CTRL_SYSTEM_STORAGE_TEST;


export const PERMISSION_ALLOW_STORAGE_ACTIVE = 'allow storage admin activate';
export const _API_CTRL_SYSTEM_STORAGE_ACTIVE = '/storage/:idOrName/activate';


export const API_CTRL_SYSTEM_STORAGE_ACTIVE = _API_CTRL_SYSTEM + _API_CTRL_SYSTEM_STORAGE_ACTIVE;


