
logging:
  enable: true
  level: debug
  transports:
    - console: { }
  loggers:
    - name: '*'
      enable: true
      level: debug
      transports:
        - console: { }



modules:
  include:
    - '**/@allgemein{,**/*}'
    - '**/@typexs{,**/*}'
    - '**/demo{,**/*}'
    - '**/testtask{,**/*}'
