
logging:
  enable: true
  level: debug
  transports:
    - console: { }
  loggers:
    - name: '*'
      enable: true
      level: debug
      transports:
        - console: { }



modules:
  disableCache: true
  paths:
    - './packages/demo-task'
  include:
    - '**/@allgemein{,**/*}'
    - '**/@typexs{,**/*}'
    - '**/demo-task{,**/*}'
    - '**/testtask{,**/*}'
