version: '3'

networks:
  dev: { }


services:
  mongo:
    image: mongo:4
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./local/mongodb:/data/db
    networks: &networks
      - dev

  redis:
    image: redis:7
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./local/redis/db:/data
    networks: *networks

  elastic:
    image: elasticsearch:7.14.2
    environment:
      - TAKE_FILE_OWNERSHIP=true
      - discovery.type=single-node
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks: *networks

  psql:
    image: postgres:16
    ports:
      - 127.0.0.1:5436:5432
    environment:
      POSTGRES_DATABASES: txsbase
      POSTGRES_USER: txsbase
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
    networks: *networks


