networks:
  dev: {}
services:

  mongo:
    image: mongo:4
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./local/mongodb:/data/db
    networks:
      - dev

  redis:
    image: redis:7
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ./local/redis/db:/data
    networks:
      - dev

  elastic:
    image: elasticsearch:7.14.2
    environment:
      - TAKE_FILE_OWNERSHIP=true
      - discovery.type=single-node
      - node.name=es01
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    networks:
      - dev

  psql:
    image: postgres:14
    ports:
      - 127.0.0.1:5436:5432
    environment:
      POSTGRES_DATABASES: txsbase
      POSTGRES_USER: txsbase
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
    networks:
      - dev


  psql-auth:
    image: postgres:14
    ports:
      - 127.0.0.1:5437:5432
    environment:
      POSTGRES_DATABASES: auth
      POSTGRES_USER: auth
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
    networks:
      - dev

  ldap:
    image: osixia/openldap:1.2.2
    ports:
      - 389:389
      - 689:689
    environment:
      LDAP_NOFILE: 10000
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug
    networks:
      - dev
