storage:
  default:
    database: '/tmp/db_${app.name}_server.db'

tasks:
  logdir: ./tmp/tasklog
  logger: 'winston'
  logging: 'file'
  access:
    - task: '*'
      access: allow

workers:
  access:
    - name: '*'
      access: allow

server:
  default:
    type: web
    framework: express
    host: localhost
    port: 4500
    routes:
      - type: routing_controller
        context: api
        routePrefix: api
      - type: static_files
        routePrefix: public
        path: packages/app/public


filesystem:
  paths:
    - ./tmp
