
eventbus:
  default:
    adapter: redis
    extra:
      host: 127.0.0.1
      port: 6379


storage:
  default:
    database: '/tmp/db_${app.name}_worker.db'

tasks:
  logdir: ./tmp/tasklog
  logger: 'winston'
  logging: 'file'
  access:
    - task: '*'
      access: allow

workers:
  access:
    - name: '*'
      access: allow

filesystem:
  paths:
    - ./tmp
