
app:
  name: app-auth


server:
  default:
    type: web
    framework: express
    host: localhost
    port: 4500

    routes:
    - type: routing_controller
      context: api
      routePrefix: api


storage:
  default:
#    type: postgres
#    database: auth
    type: sqlite
#    username: auth
#    port: 5437
    synchronize: true
    # database: ':memory:'
    database: 'tmp/db_${app.name}.db'
    connectOnStartup: true
    # logger: simple-console
    # logging: all


modules:
  exclude:
    - '**/@typexs/search{,**/*}'
    - '**/@typexs/pipelines{,**/*}'
